# Project information
site_name: spexread
site_description: 'A module for reading Princeton Instruments SPE files (version 2.x and 3.0) captured by WinSpec or LightField'
site_author: Antoine Salden
site_url: https://github.com/AntoineTUE/spexread
copyright: 'Copyright &copy; Antoine Salden 2025-present'
repo_name: spexread
repo_url: https://github.com/AntoineTUE/spexread


docs_dir: docs
site_dir: site
theme:
  name: material
  language: en
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/material-camera-iris
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.tabs.sticky
    - navigation.footer
    - toc.integrate
    - toc.follow
    - content.code.copy

watch:
- src/spexread

plugins:
  search: {}
  autorefs: {}
  include-markdown: {}
  gh-admonitions: {}
  mike:
    alias_type: copy
    canonical_version: "latest"
  git-revision-date-localized:
    exclude:
      - reference/*
    fallback_to_build_date: true
    enable_creation_date: true
  api-autonav:
    modules: ['src/spexread']
    exclude_private: true
    nav_section_title: API Reference
    module_options:
      spexread.structdef:
        members: [EnumDataType,EnumOrientation,SPEStructure, ROIInfo,CalibrationStruct,SPEInfoHeader]
        summary: false
        show_bases: false
  section-index: {}
  mkdocstrings:
    default_handler: python_xref
    handlers:
      python_xref:
        paths:
          - src
        options:
          members_order: source
          relative_crossrefs: true
          signature_crossrefs: true
          docstring_style: google
          docstring_options:
            ignore_init_summary: yes
          filters:
            - "!^__"
          merge_init_into_class: yes
          show_submodules: no
          show_root_heading: true
          show_root_full_path: true
          show_root_members_full_path: false
          show_if_no_docstring: true
          show_docstring_attributes: true
          show_docstring_functions: true
          annotations_path: brief
          separate_signature: true
          line_length: 120
          show_signature_annotations: true
          show_bases: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_labels: false
          summary: true
          extra:
            show_docstrings_modules: true
  mkdocs-jupyter:
    include_requirejs: true
    include_source: true
    include: ["*.ipynb"]
    ignore: ["*/.ipynb_checkpoints/*.ipynb"]

markdown_extensions:
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: AntoineTUE
      repo: spexread
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AntoineTUE/spexread

extra_javascript:
  - assets/javascript/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.min.js

nav:
  - Home: index.md
  - API Reference
  - License: license.md
